name: Test

on:
  pull_request:
    paths-ignore:
      - "static/**"
    branches: [master]
  push:
    paths-ignore:
      - "static/**"
    branches: [master]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up Go 1.16.3
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.3
        id: go
      - name: Test
        run: go test -v ./... 
